version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.13

    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run: sudo apt update
      - run: sudo apt install libboost-all-dev
      - run: sudo apt install libtbb-dev
      - run: go env -w GOPRIVATE=github.com/arcology
      - run: sudo bash .circleci/download_artifacts.sh
      # - run: sudo ln -s /home/circleci/project/liburlarbitrator.so /usr/local/lib
      - run: go build ./...
      - run: export LD_LIBRARY_PATH=/usr/local/lib && go test -v ./evm/